export const ACTIONS = {
  GET_INGR: "GET_INGR",
  GET_ORDER: "GET_ORDER",
  GET_CONSTRUCTOR_INGR: "GET_CONSTRUCTOR_INGR",
  GET_CURRENT_INGR: "GET_CURRENT_INGR",

  TOGGLE_LOADING_DATA: "TOGGLE_LOADING_DATA",
  TOGGLE_LOADING_ORDER: "TOGGLE_LOADING_ORDER",
};
