export const ACTIONS = {
  // ingredients
  GET_INGREDIENTS: "GET_INGREDIENTS",
  GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS",
  GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED",

  SET_CURRENT_INGREDIENT: "SET_CURRENT_INGREDIENT",
  SET_CURRENT_TAB: "SET_CURRENT_TAB",

  // constructor
  GET_ORDER: "GET_ORDER",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_FAILED: "GET_ORDER_FAILED",

  DRAG_INNER_INGREDIENT: "DRAG_INNER_INGREDIENT",
  DRAG_OUTER_INGREDIENT: "DRAG_OUTER_INGREDIENT",
  SORT_INNER_INGREDIENT: "SORT_INNER_INGREDIENT",
  RESET_CONSTRUCTOR: "RESET_CONSTRUCTOR",

  DELETE_CONSTRUCTOR_INGREDIENT: "DELETE_CONSTRUCTOR_INGREDIENT",

  TOGGLE_LOADING_ORDER: "TOGGLE_LOADING_ORDER",

  // login
  LOGIN_FORM_SET_VALUE: "LOGIN_FORM_SET_VALUE",
};
