export const ACTIONS = {
  GET_INGR: "GET_INGR",
  GET_ORDER: "GET_ORDER",
  GET_CURRENT_INGR: "GET_CURRENT_INGR",
  DRAG_INNER: "DRAG_INNER",
  DRAG_OUTER: "DRAG_OUTER",

  GET_CONSTRUCTOR_INGR: "GET_CONSTRUCTOR_INGR",
  DELETE_CONSTRUCTOR_INGR: "DELETE_CONSTRUCTOR_INGR",

  SET_CURRENT_TAB: "SET_CURRENT_TAB",

  TOGGLE_LOADING_DATA: "TOGGLE_LOADING_DATA",
  TOGGLE_LOADING_ORDER: "TOGGLE_LOADING_ORDER",
};
